k10plus: validate enrichment

diff --git a/k10plus/enrich-with-ddc b/k10plus/enrich-with-ddc
--- a/k10plus/enrich-with-ddc
+++ b/k10plus/enrich-with-ddc
@@ -1,3 +1,7 @@
 #!/bin/bash
-DDC=$1
-./records-with-ddc "$DDC" | ./enrich.pl "$DDC"
+set -e
+
+PICA=`./records-with-ddc "$1" | ./enrich.pl "$1"`
+
+echo "$PICA" | picadata -s avram.json -u  # will exit on error
+echo "$PICA"
